"""Blind-author fixture description template and input-bundle assembler.

Implements fixture plan §2 (reviewer findings 1-2): the author-facing fixture
description is generated by script from a fixed template filled only from the
`fixture` section of proofdeploy.yml. The template is frozen and hashed before
the first author run; the bundle assembler verifies the hash fail-closed.

The author's full input bundle (diff, repo snapshot without git history,
fixture description) is assembled by script from an allowlist, never by hand.

Reviewer finding 6: snapshots are created by script via `git archive <B>`
into an empty directory; the manifest records the source SHA.
"""

from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
import tarfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

# Placeholders the template may contain. Anything else in {braces} fails
# closed at render time — except ${AUTH_TOKEN}, which is a runner-injected
# credential placeholder and must pass through untouched.
TEMPLATE_FIELDS = ("repo_name", "seed_note", "auth_mechanism", "auth_scope", "flags_note")

# The author's input bundle contains exactly these items, nothing else.
# skill-author.md is the generated author copy (hash e42f12d7...); the audited
# source skill.md never enters the bundle.
BUNDLE_ALLOWLIST = ("diff.patch", "snapshot", "fixture-description.txt", "skill-author.md")

# Expected sha256 of the generated author copy. The assembler verifies this
# fail-closed: a different skill means a different measurement.
EXPECTED_SKILL_HASH = "e42f12d71ea9f5ceee0f6d13b553f7cb13426954053db684ae4e2a6a8d73f5f9"

TEMPLATE_FILENAME = "fixture_template.txt"


def template_path() -> Path:
    """Path to the frozen template file shipped with the package."""
    return Path(__file__).with_name(TEMPLATE_FILENAME)


def template_hash(path: str | Path | None = None) -> str:
    """sha256 of the template file bytes (comments included)."""
    p = Path(path) if path else template_path()
    return hashlib.sha256(p.read_bytes()).hexdigest()


def _strip_comments(text: str) -> str:
    """Remove `#` comment lines; the author never sees them."""
    lines = [ln for ln in text.splitlines() if not ln.lstrip().startswith("#")]
    return "\n".join(lines).strip() + "\n"


def render_description(template_text: str, fields: dict[str, str]) -> str:
    """Fill the template's {placeholders} from the yml fixture mapping.

    Fail-closed: every TEMPLATE_FIELD must be present and a non-empty string;
    after substitution, any remaining {...} other than ${AUTH_TOKEN} raises.
    ${AUTH_TOKEN} passes through untouched for the runner to inject.
    """
    missing = [f for f in TEMPLATE_FIELDS if not fields.get(f)]
    if missing:
        raise ValueError(f"fixture mapping missing fields: {', '.join(missing)}")
    for f in TEMPLATE_FIELDS:
        if not isinstance(fields[f], str):
            raise ValueError(f"fixture field '{f}' must be a string")

    body = _strip_comments(template_text)
    # Protect the runner placeholder from brace scanning, then restore it.
    sentinel = "\x00AUTH_TOKEN\x00"
    body = body.replace("${AUTH_TOKEN}", sentinel)
    for f in TEMPLATE_FIELDS:
        body = body.replace("{" + f + "}", fields[f])
    if "{" in body or "}" in body:
        raise ValueError(
            "template contains an unknown {placeholder}: only the five fixture fields are allowed"
        )
    return body.replace(sentinel, "${AUTH_TOKEN}")


@dataclass
class AuthorBundle:
    """Paths of an assembled author input bundle."""

    root: Path
    diff: Path
    snapshot: Path
    description: Path
    skill: Path
    manifest: Path


def _sha256_file(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def _check_snapshot_tree(snap: Path) -> None:
    """Fail closed on anything that could smuggle history or outside content.

    Refuses `.git` at any depth (a submodule or vendored checkout can carry
    history in a nested `.git`) and refuses symlinks altogether (`copytree`
    would otherwise follow a link pointing outside the snapshot).
    """
    for p in snap.rglob("*"):
        if p.name == ".git":
            raise ValueError(f"snapshot must not contain .git history: {p}")
        if p.is_symlink():
            raise ValueError(f"snapshot must not contain symlinks: {p}")


def _tree_hash(root: Path) -> str:
    """Deterministic hash of a directory tree.

    sha256 over each file's sorted relative posix path plus its content
    hash, so the manifest records exactly which snapshot went into the
    bundle.
    """
    h = hashlib.sha256()
    files = sorted(p for p in root.rglob("*") if p.is_file() and not p.is_symlink())
    for p in files:
        h.update(p.relative_to(root).as_posix().encode() + b"\x00")
        h.update(_sha256_file(p).encode() + b"\x00")
    h.update(f"{len(files)} files".encode())
    return h.hexdigest()


def _check_output_dir(out: Path) -> None:
    """The bundle directory must be empty (or absent) before assembly.

    Anything already in the output directory would otherwise ride along
    into the author's bundle outside the allowlist.
    """
    if out.exists() and not out.is_dir():
        raise ValueError(f"output path exists and is not a directory: {out}")
    if out.exists() and any(out.iterdir()):
        raise ValueError(f"output directory is not empty: {out}; assemble into an empty directory")


@dataclass
class Snapshot:
    """A repo snapshot created by script from a git commit."""

    dir: Path
    sha: str  # full resolved commit SHA; recorded as the manifest's source_sha


def _git(repo_dir: Path, *args: str) -> subprocess.CompletedProcess[bytes]:
    """Run git in repo_dir, returning the completed process (never raising)."""
    return subprocess.run(
        ["git", "-C", str(repo_dir), *args],
        capture_output=True,
        check=False,
    )


def create_snapshot(
    *,
    repo_dir: str | Path,
    commit_rev: str,
    output_dir: str | Path,
) -> Snapshot:
    """Create a repo snapshot at <commit_rev> via `git archive`.

    Resolves <commit_rev> to its full SHA with `git rev-parse`, then streams
    `git archive <sha>` out of repo_dir and extracts it into output_dir,
    which must be absent or empty (fail closed). `git archive` emits file
    contents only — no history, no `.git` directory — so there is nothing
    to smuggle by construction.

    The archive streams through a pipe (never fully buffered in memory) and
    each member is validated before extraction: symlinks, hardlinks, and
    non-file/non-dir members are refused outright, and any member whose
    path would escape output_dir raises.

    Returns the snapshot directory and the resolved full SHA. Pass the SHA
    as `source_sha` to `assemble_author_bundle` so the manifest records
    exactly which commit the snapshot came from.

    Fail-closed: unknown rev, non-empty output dir, `git archive` failure,
    or an archive member that is a link or would extract outside output_dir
    all raise.
    """
    repo = Path(repo_dir)
    out = Path(output_dir)

    rev = _git(repo, "rev-parse", "--verify", f"{commit_rev}^{{commit}}")
    if rev.returncode != 0:
        raise ValueError(
            f"cannot resolve commit {commit_rev!r} in {repo}: {rev.stderr.decode().strip()}"
        )
    sha = rev.stdout.decode().strip()

    _check_output_dir(out)
    out.mkdir(parents=True, exist_ok=True)

    out_resolved = out.resolve()
    proc = subprocess.Popen(
        ["git", "-C", str(repo), "archive", sha],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    try:
        assert proc.stdout is not None  # for mypy: Popen with PIPE sets it
        with tarfile.open(fileobj=proc.stdout, mode="r|") as tf:
            for member in tf:
                if member.issym() or member.islnk():
                    raise ValueError(f"archive member is a link, refused: {member.name}")
                if not (member.isfile() or member.isdir()):
                    raise ValueError(f"archive member is not a file or dir, refused: {member.name}")
                target = (out / member.name).resolve()
                if not str(target).startswith(str(out_resolved) + "/"):
                    raise ValueError(f"archive member escapes snapshot dir: {member.name}")
                tf.extract(member, out)
    finally:
        # If validation raised mid-stream, stop the producer.
        if proc.poll() is None:
            proc.kill()
        _, stderr = proc.communicate()
    if proc.returncode != 0:
        raise ValueError(f"git archive {sha} failed in {repo}: {stderr.decode().strip()}")
    return Snapshot(dir=out, sha=sha)


def _check_bundle_contents(out: Path) -> None:
    """After assembly the bundle must contain exactly the allowlist."""
    actual = sorted(p.name for p in out.iterdir())
    if actual != sorted(BUNDLE_ALLOWLIST):
        raise ValueError(
            f"bundle contents {actual} do not match the allowlist {sorted(BUNDLE_ALLOWLIST)}"
        )


def assemble_author_bundle(
    *,
    diff_path: str | Path,
    snapshot_dir: str | Path,
    yml_fixture: dict[str, str],
    output_dir: str | Path,
    expected_template_hash: str,
    template_file: str | Path | None = None,
    source_sha: str | None = None,
    diff_range: str | None = None,
    skill_path: str | Path | None = None,
    expected_skill_hash: str = EXPECTED_SKILL_HASH,
) -> AuthorBundle:
    """Assemble the blind author's input bundle from the allowlist.

    Verifies the frozen template hash before rendering (fail closed), renders
    the fixture description from the yml fixture mapping, copies the diff,
    the snapshot, and the generated author skill copy, and writes a manifest
    NEXT TO the bundle (never inside it — the manifest may record source SHAs
    and diff ranges that must not reach the author).

    The skill hash is verified fail-closed and recorded in the manifest, so
    every run is tied to exactly the registered skill content.

    Fail-closed throughout: template hash mismatch, skill hash mismatch,
    non-empty output dir, `.git` at any depth in the snapshot, symlinks in
    the snapshot, or a final bundle whose contents differ from the allowlist
    all raise.
    """
    tpath = Path(template_file) if template_file else template_path()
    actual_hash = hashlib.sha256(tpath.read_bytes()).hexdigest()
    if actual_hash != expected_template_hash:
        raise ValueError(
            "template hash mismatch: the frozen template changed; prior author runs are invalidated"
        )

    diff_p = Path(diff_path)
    snap_p = Path(snapshot_dir)
    out = Path(output_dir)
    if not diff_p.is_file():
        raise ValueError(f"diff not found: {diff_p}")
    if not snap_p.is_dir():
        raise ValueError(f"snapshot dir not found: {snap_p}")
    _check_snapshot_tree(snap_p)
    _check_output_dir(out)

    description = render_description(tpath.read_text(encoding="utf-8"), yml_fixture)

    out.mkdir(parents=True, exist_ok=True)
    out_diff = out / "diff.patch"
    out_snap = out / "snapshot"
    out_desc = out / "fixture-description.txt"
    out_skill = out / "skill-author.md"
    shutil.copyfile(diff_p, out_diff)
    # copytree without symlinks=True never creates symlinks, but the source
    # tree was already checked above; re-check the copy belt and braces.
    shutil.copytree(snap_p, out_snap)
    _check_snapshot_tree(out_snap)
    out_desc.write_text(description, encoding="utf-8")

    # The generated author copy goes in the bundle; its hash is verified
    # fail-closed and recorded in the manifest. The audited source never
    # enters the bundle.
    if skill_path is None:
        raise ValueError("skill_path is required: the author bundle must include skill-author.md")
    skill_p = Path(skill_path)
    if not skill_p.is_file():
        raise ValueError(f"skill file not found: {skill_p}")
    skill_hash = _sha256_file(skill_p)
    if skill_hash != expected_skill_hash:
        raise ValueError(
            "skill hash mismatch: expected the registered author copy; "
            "a different skill means a different measurement"
        )
    shutil.copyfile(skill_p, out_skill)

    _check_bundle_contents(out)

    manifest = {
        "assembled_at": datetime.now(timezone.utc).isoformat(),
        "template_sha256": actual_hash,
        "skill_sha256": skill_hash,
        "allowlist": list(BUNDLE_ALLOWLIST),
        "snapshot_tree_sha256": _tree_hash(out_snap),
        "files": {
            "diff.patch": _sha256_file(out_diff),
            "fixture-description.txt": _sha256_file(out_desc),
            "skill-author.md": skill_hash,
        },
    }
    # Source SHAs and diff ranges live in the manifest, which sits next to
    # the bundle — never inside it, never reaching the author.
    if source_sha is not None:
        manifest["source_sha"] = source_sha
    if diff_range is not None:
        manifest["diff_range"] = diff_range
    out_manifest = out.with_name(out.name + ".manifest.json")
    out_manifest.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return AuthorBundle(
        root=out,
        diff=out_diff,
        snapshot=out_snap,
        description=out_desc,
        skill=out_skill,
        manifest=out_manifest,
    )
