"""Blind-author fixture description template and input-bundle assembler.

Implements fixture plan §2 (reviewer findings 1-2): the author-facing fixture
description is generated by script from a fixed template filled only from the
`fixture` section of proofdeploy.yml. The template is frozen and hashed before
the first author run; the bundle assembler verifies the hash fail-closed.

The author's full input bundle (diff, repo snapshot without git history,
fixture description) is assembled by script from an allowlist, never by hand.
"""

from __future__ import annotations

import hashlib
import json
import shutil
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

# Placeholders the template may contain. Anything else in {braces} fails
# closed at render time — except ${AUTH_TOKEN}, which is a runner-injected
# credential placeholder and must pass through untouched.
TEMPLATE_FIELDS = ("repo_name", "seed_note", "auth_mechanism", "auth_scope", "flags_note")

# The author's input bundle contains exactly these three items, nothing else.
BUNDLE_ALLOWLIST = ("diff.patch", "snapshot", "fixture-description.txt")

TEMPLATE_FILENAME = "fixture_template.txt"


def template_path() -> Path:
    """Path to the frozen template file shipped with the package."""
    return Path(__file__).with_name(TEMPLATE_FILENAME)


def template_hash(path: str | Path | None = None) -> str:
    """sha256 of the template file bytes (comments included)."""
    p = Path(path) if path else template_path()
    return hashlib.sha256(p.read_bytes()).hexdigest()


def _strip_comments(text: str) -> str:
    """Remove `#` comment lines; the author never sees them."""
    lines = [ln for ln in text.splitlines() if not ln.lstrip().startswith("#")]
    return "\n".join(lines).strip() + "\n"


def render_description(template_text: str, fields: dict[str, str]) -> str:
    """Fill the template's {placeholders} from the yml fixture mapping.

    Fail-closed: every TEMPLATE_FIELD must be present and a non-empty string;
    after substitution, any remaining {...} other than ${AUTH_TOKEN} raises.
    ${AUTH_TOKEN} passes through untouched for the runner to inject.
    """
    missing = [f for f in TEMPLATE_FIELDS if not fields.get(f)]
    if missing:
        raise ValueError(f"fixture mapping missing fields: {', '.join(missing)}")
    for f in TEMPLATE_FIELDS:
        if not isinstance(fields[f], str):
            raise ValueError(f"fixture field '{f}' must be a string")

    body = _strip_comments(template_text)
    # Protect the runner placeholder from brace scanning, then restore it.
    sentinel = "\x00AUTH_TOKEN\x00"
    body = body.replace("${AUTH_TOKEN}", sentinel)
    for f in TEMPLATE_FIELDS:
        body = body.replace("{" + f + "}", fields[f])
    if "{" in body or "}" in body:
        raise ValueError(
            "template contains an unknown {placeholder}: "
            "only the five fixture fields are allowed"
        )
    return body.replace(sentinel, "${AUTH_TOKEN}")


@dataclass
class AuthorBundle:
    """Paths of an assembled author input bundle."""

    root: Path
    diff: Path
    snapshot: Path
    description: Path
    manifest: Path


def _sha256_file(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def assemble_author_bundle(
    *,
    diff_path: str | Path,
    snapshot_dir: str | Path,
    yml_fixture: dict[str, str],
    output_dir: str | Path,
    expected_template_hash: str,
    template_file: str | Path | None = None,
) -> AuthorBundle:
    """Assemble the blind author's input bundle from the allowlist.

    Verifies the frozen template hash before rendering (fail closed), renders
    the fixture description from the yml fixture mapping, copies the diff and
    the snapshot (refusing snapshots that contain .git), and writes a manifest
    recording the sha256 of every bundle item.
    """
    tpath = Path(template_file) if template_file else template_path()
    actual_hash = hashlib.sha256(tpath.read_bytes()).hexdigest()
    if actual_hash != expected_template_hash:
        raise ValueError(
            "template hash mismatch: the frozen template changed; "
            "prior author runs are invalidated"
        )

    diff_p = Path(diff_path)
    snap_p = Path(snapshot_dir)
    out = Path(output_dir)
    if not diff_p.is_file():
        raise ValueError(f"diff not found: {diff_p}")
    if not snap_p.is_dir():
        raise ValueError(f"snapshot dir not found: {snap_p}")
    if (snap_p / ".git").exists():
        raise ValueError("snapshot must not contain .git history")

    description = render_description(tpath.read_text(encoding="utf-8"), yml_fixture)

    out.mkdir(parents=True, exist_ok=True)
    out_diff = out / "diff.patch"
    out_snap = out / "snapshot"
    out_desc = out / "fixture-description.txt"
    shutil.copyfile(diff_p, out_diff)
    if out_snap.exists():
        shutil.rmtree(out_snap)
    shutil.copytree(snap_p, out_snap)
    # Belt and braces: the copy must not have smuggled .git in either.
    if (out_snap / ".git").exists():
        raise ValueError("snapshot copy contains .git history")
    out_desc.write_text(description, encoding="utf-8")

    manifest = {
        "assembled_at": datetime.now(timezone.utc).isoformat(),
        "template_sha256": actual_hash,
        "allowlist": list(BUNDLE_ALLOWLIST),
        "files": {
            "diff.patch": _sha256_file(out_diff),
            "fixture-description.txt": _sha256_file(out_desc),
        },
    }
    out_manifest = out / "manifest.json"
    out_manifest.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return AuthorBundle(
        root=out, diff=out_diff, snapshot=out_snap,
        description=out_desc, manifest=out_manifest,
    )
